services:
  - type: web
    name: rag-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: sh entrypoint.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"
      - key: USE_REDIS
        value: "true"
      - key: CHROMA_PATH
        value: "/opt/render/project/src/chroma_store"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false        # you paste this from Neon
      - key: REDIS_URL
        sync: false        # you paste this from Upstash
      - key: GEMINI_API_KEY_1
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GEMINI_API_KEY_3
        sync: false
      - key: GEMINI_API_KEY_4
        sync: false
      - key: LLM_MODEL_TYPE
        value: "gemini-2.5-flash"
      - key: ALLOWED_HOSTS
        sync: false        # paste your render URL after deploy
      - key: CORS_ALLOWED_ORIGINS
        sync: false        # paste your vercel URL after deploy