# Generated by Django 6.0.3 on 2026-03-25 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('sector', models.CharField(choices=[('Technology', 'Technology'), ('Clean Energy', 'Clean Energy'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Financial Services', 'Financial Services'), ('Manufacturing', 'Manufacturing'), ('Consumer Goods', 'Consumer Goods'), ('Other', 'Other')], default='Other', max_length=100)),
                ('market_cap', models.BigIntegerField(help_text='Market capitalisation in USD')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (Jan–Mar)'), (2, 'Q2 (Apr–Jun)'), (3, 'Q3 (Jul–Sep)'), (4, 'Q4 (Oct–Dec)')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('revenue', models.BigIntegerField(help_text='Total revenue in USD')),
                ('net_income', models.BigIntegerField(help_text='Net income (profit) in USD')),
                ('operating_expenses', models.BigIntegerField(help_text='Total operating expenses in USD')),
                ('debt_to_equity', models.DecimalField(decimal_places=2, help_text='Debt-to-Equity ratio (e.g., 1.82 means 1.82x leveraged)', max_digits=6)),
                ('analyst_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='rag_app.company')),
            ],
            options={
                'verbose_name': 'Quarterly Financials',
                'verbose_name_plural': 'Quarterly Financials',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('company', 'quarter', 'year')},
            },
        ),
    ]
